### ISSUE TITLE
async

### ISSUE THREAD

**Issue by steveoh** [steveoh/esrislurp#8]
async went to v1. Test with that and see if this addresses the node version issues.

https://github.com/steveoh/grunt-esri-slurp/issues/35

**Comment by sfabijanski** [comment]
Issue appears be with request, not async. There are a few things going on here that need to be addressed. The simple one is handling the error inside the request callback with either a check on error or a check on body. That missing check leads to the length error noted here https://github.com/steveoh/grunt-esri-slurp/issues/35. In my test environment I've added <code>if (body and body.length < 1)</code> but a check on error like <code>if ( !error && body.length < 1 )</code> might be a better test.

There also appears to be a upper limit being reached that is throwing errors on getaddrinfo in request. It is throwing DNS related errors after that limit is being reached. There are a few issues on request that led me to test the requests using the IP address to js.arcgis.com instead of the name. When I updated the baseUrl with the IP address (54.239.152.16) the script completed on the newer node versions where it was previously failing.  Worth a try in debugging the problem though not a final solution.

When I get the time, I'll try some more testing and try to get a proper pull request in place.

**Comment by sfabijanski** [comment]
I put together a gist (https://gist.github.com/sfabijanski/9051d95523aea3f377c8) with an updated esrislurp.js file. With the addition of a new http agent, the script runs to completion on an Ubuntu 15.04 box using io.js v1.8.1. The gist also includes checks for error and body in the request and moves the eachLimit callback inside of the writeFile call (per caolan's recommendation on using eachLimit). Tested using @twayson's esri-slurp-example project.

**Comment by steveoh** [comment]
Have you tried this on node 0.12.4? Lets package this into a PR to play with it easier.

**Comment by sfabijanski** [comment]
Testing now with 0.12.4 using nvm against the esri-slurp-example and my own project.  I put the gist together rather quickly and now see a few errors I introduced--body check is faulty logic and really could just be a check like <code>if(!body) { ...</code>. I'll try to put together a better PR in the next day or so.

You're welcome and thanks. This project has been invaluable to me in getting my current internal application running and deploying smoothly.

**Comment by steveoh** [comment]
closed with 9163c9ea593ad7cbd1a99763792cd0320e029f9e
